// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UlkemWebApp.Models;

#nullable disable

namespace UlkemWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CicekGonderimAmaci", b =>
                {
                    b.Property<int>("CiceklerId")
                        .HasColumnType("int");

                    b.Property<int>("GonderimAmaclariId")
                        .HasColumnType("int");

                    b.HasKey("CiceklerId", "GonderimAmaclariId");

                    b.HasIndex("GonderimAmaclariId");

                    b.ToTable("CicekGonderimAmaci");
                });

            modelBuilder.Entity("UlkemWebApp.Models.BlogYazisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotografUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YayimTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BlogYazisi");
                });

            modelBuilder.Entity("UlkemWebApp.Models.Cicek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CicekTuruId")
                        .HasColumnType("int");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FotografUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KampanyaId")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OzelGunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CicekTuruId");

                    b.HasIndex("KampanyaId");

                    b.HasIndex("OzelGunId");

                    b.ToTable("Cicek");
                });

            modelBuilder.Entity("UlkemWebApp.Models.CicekTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CicekTuru");
                });

            modelBuilder.Entity("UlkemWebApp.Models.GonderimAmaci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GonderimAmaci");
                });

            modelBuilder.Entity("UlkemWebApp.Models.Hakkimizda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hakkimizda");
                });

            modelBuilder.Entity("UlkemWebApp.Models.IletisimFormu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GonderimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IletisimFormu");
                });

            modelBuilder.Entity("UlkemWebApp.Models.Kampanya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IndirimOrani")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Kampanya");
                });

            modelBuilder.Entity("UlkemWebApp.Models.KargoFiyati", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CicekId")
                        .HasColumnType("int");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TeslimatBolgesiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CicekId");

                    b.HasIndex("TeslimatBolgesiId");

                    b.ToTable("KargoFiyati");
                });

            modelBuilder.Entity("UlkemWebApp.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SepetId")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SepetId");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("UlkemWebApp.Models.OzelGun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OzelGun");
                });

            modelBuilder.Entity("UlkemWebApp.Models.Sepet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MusteriId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sepet");
                });

            modelBuilder.Entity("UlkemWebApp.Models.SepetUrunu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<int>("CicekId")
                        .HasColumnType("int");

                    b.Property<int>("SepetId")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CicekId");

                    b.HasIndex("SepetId");

                    b.ToTable("SepetUrunu");
                });

            modelBuilder.Entity("UlkemWebApp.Models.Siparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("MusteriAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriAdres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriTelefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Siparis");
                });

            modelBuilder.Entity("UlkemWebApp.Models.SiparisUrunu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<int>("CicekId")
                        .HasColumnType("int");

                    b.Property<int>("SiparisId")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CicekId");

                    b.HasIndex("SiparisId");

                    b.ToTable("SiparisUrunu");
                });

            modelBuilder.Entity("UlkemWebApp.Models.TeslimatBolgesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BolgeAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TeslimatUcreti")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TeslimatBolgesi");
                });

            modelBuilder.Entity("UlkemWebApp.Models.Yorum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BlogYazisiId")
                        .HasColumnType("int");

                    b.Property<int>("CicekId")
                        .HasColumnType("int");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Puan")
                        .HasColumnType("int");

                    b.Property<DateTime>("YorumTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BlogYazisiId");

                    b.HasIndex("CicekId");

                    b.ToTable("Yorum");
                });

            modelBuilder.Entity("CicekGonderimAmaci", b =>
                {
                    b.HasOne("UlkemWebApp.Models.Cicek", null)
                        .WithMany()
                        .HasForeignKey("CiceklerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UlkemWebApp.Models.GonderimAmaci", null)
                        .WithMany()
                        .HasForeignKey("GonderimAmaclariId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UlkemWebApp.Models.Cicek", b =>
                {
                    b.HasOne("UlkemWebApp.Models.CicekTuru", "CicekTuru")
                        .WithMany("Cicekler")
                        .HasForeignKey("CicekTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UlkemWebApp.Models.Kampanya", null)
                        .WithMany("IndirimliCicekler")
                        .HasForeignKey("KampanyaId");

                    b.HasOne("UlkemWebApp.Models.OzelGun", null)
                        .WithMany("OnerilenCicekler")
                        .HasForeignKey("OzelGunId");

                    b.Navigation("CicekTuru");
                });

            modelBuilder.Entity("UlkemWebApp.Models.KargoFiyati", b =>
                {
                    b.HasOne("UlkemWebApp.Models.Cicek", "Cicek")
                        .WithMany("CargoFiyatlari")
                        .HasForeignKey("CicekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UlkemWebApp.Models.TeslimatBolgesi", "TeslimatBolgesi")
                        .WithMany("CargoFiyatlari")
                        .HasForeignKey("TeslimatBolgesiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cicek");

                    b.Navigation("TeslimatBolgesi");
                });

            modelBuilder.Entity("UlkemWebApp.Models.Kullanici", b =>
                {
                    b.HasOne("UlkemWebApp.Models.Sepet", "Sepet")
                        .WithMany()
                        .HasForeignKey("SepetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sepet");
                });

            modelBuilder.Entity("UlkemWebApp.Models.SepetUrunu", b =>
                {
                    b.HasOne("UlkemWebApp.Models.Cicek", "Cicek")
                        .WithMany()
                        .HasForeignKey("CicekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UlkemWebApp.Models.Sepet", "Sepet")
                        .WithMany("SepetUrunleri")
                        .HasForeignKey("SepetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cicek");

                    b.Navigation("Sepet");
                });

            modelBuilder.Entity("UlkemWebApp.Models.Siparis", b =>
                {
                    b.HasOne("UlkemWebApp.Models.Kullanici", null)
                        .WithMany("Siparisler")
                        .HasForeignKey("KullaniciId");
                });

            modelBuilder.Entity("UlkemWebApp.Models.SiparisUrunu", b =>
                {
                    b.HasOne("UlkemWebApp.Models.Cicek", "Cicek")
                        .WithMany()
                        .HasForeignKey("CicekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UlkemWebApp.Models.Siparis", "Siparis")
                        .WithMany("SiparisUrunleri")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cicek");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("UlkemWebApp.Models.Yorum", b =>
                {
                    b.HasOne("UlkemWebApp.Models.BlogYazisi", null)
                        .WithMany("Yorumlar")
                        .HasForeignKey("BlogYazisiId");

                    b.HasOne("UlkemWebApp.Models.Cicek", "Cicek")
                        .WithMany()
                        .HasForeignKey("CicekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cicek");
                });

            modelBuilder.Entity("UlkemWebApp.Models.BlogYazisi", b =>
                {
                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("UlkemWebApp.Models.Cicek", b =>
                {
                    b.Navigation("CargoFiyatlari");
                });

            modelBuilder.Entity("UlkemWebApp.Models.CicekTuru", b =>
                {
                    b.Navigation("Cicekler");
                });

            modelBuilder.Entity("UlkemWebApp.Models.Kampanya", b =>
                {
                    b.Navigation("IndirimliCicekler");
                });

            modelBuilder.Entity("UlkemWebApp.Models.Kullanici", b =>
                {
                    b.Navigation("Siparisler");
                });

            modelBuilder.Entity("UlkemWebApp.Models.OzelGun", b =>
                {
                    b.Navigation("OnerilenCicekler");
                });

            modelBuilder.Entity("UlkemWebApp.Models.Sepet", b =>
                {
                    b.Navigation("SepetUrunleri");
                });

            modelBuilder.Entity("UlkemWebApp.Models.Siparis", b =>
                {
                    b.Navigation("SiparisUrunleri");
                });

            modelBuilder.Entity("UlkemWebApp.Models.TeslimatBolgesi", b =>
                {
                    b.Navigation("CargoFiyatlari");
                });
#pragma warning restore 612, 618
        }
    }
}
